version: "3"

services:
    webdriver:
        image: selenium/standalone-chrome:4.0.0-rc-3-20211010
        shm_size: 2gb
        ports:
            - 4444:4444
        networks:
            - cookie-clicker-afk
        environment:
            - SE_NODE_SESSION_TIMEOUT=-1
        restart: unless-stopped
    
    worker:
        build: .
        networks:
            - cookie-clicker-afk
        depends_on:
            - webdriver
        volumes:
            - worker-storage:/app/
        restart: unless-stopped

networks:
    cookie-clicker-afk:

volumes:
    worker-storage:
