version: "3"

services:
    webdriver:
        image: selenium/standalone-chrome:4.0.0-rc-3-20211010
        shm_size: 2gb
        ports:
            - 4444:4444
        networks:
            - cookie-clicker-afk
        environment:
            - SE_NODE_SESSION_TIMEOUT=86400
        restart: unless-stopped
    
    worker:
        build: .
        networks:
            - cookie-clicker-afk
        depends_on:
            - webdriver
        # environment:
            # - TELEGRAM_BOT_TOKEN={{ TELEGRAM_BOT_TOKEN }}
            # - TELEGRAM_ADMIN_ID={{ TELEGRAM_ADMIN_ID }}
            # - DRIVER_URL={{ DRIVER_URL }}
        restart: unless-stopped

networks:
    cookie-clicker-afk:
