version: "3"

services:
    webdriver:
        image: selenium/standalone-chrome:4.8.1
        shm_size: 2gb
        ports:
            - 4444:4444
        environment:
            - SE_NODE_SESSION_TIMEOUT=86400
        restart: unless-stopped
